### PR TITLE
<add> Implement server-side JS FizzBuzz

### PR DESCRIPTION
**Pull request by adyates**
There's definitely some whitespace to fix, not sure about other issues.

[Review on Reviewable](https://reviewable.io/reviews/adyates/fizzbuzz-the-musical/8)

### CODE REVIEW

**Comment by nicolasartman** [comment]
Review status: 0 of 7 files reviewed, 13 unresolved discussions, all commit checks successful.

---

<sup>**[.gitignore, line 5 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpW6gF99ME-fxeV_Bq9)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/.gitignore#L5)):</sup>
the usual rule i see is just `node_modules`. might also want to excude .DS_Store

---

<sup>**[nodejs/build/fbtest.js, line 4 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpW4n2_tJFwaUM32xn2)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/nodejs/build/fbtest.js#L4)):</sup>
missing indentation starting here

---

<sup>**[nodejs/build/fbtest.js, line 6 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpW5_Q10XA0QAKJETEt)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/nodejs/build/fbtest.js#L6)):</sup>
typically you'd collect these values in an array and then .join it

---

<sup>**[nodejs/build/fbtest.js, line 10 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpW5KGjDPqk9TEx5uop)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/nodejs/build/fbtest.js#L10)):</sup>
spaces. so `var i = 1`. some js folks advocate never using ++ and instead using += 1. up to you.

---

<sup>**[nodejs/build/fbtest.js, line 11 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpW4u9swzsWz1R7m22-)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/nodejs/build/fbtest.js#L11)):</sup>
indent

---

<sup>**[nodejs/build/fbtest.js, line 17 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpW5rhNpqFdw_fxLyCI)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/nodejs/build/fbtest.js#L17)):</sup>
not sure what this is

---

<sup>**[nodejs/build/fbtest.js, line 18 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpW5zh34yBobffXxvnf)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/nodejs/build/fbtest.js#L18)):</sup>
all the code below should really be broken into a separate file

---

<sup>**[nodejs/build/fbtest.js, line 36 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpW66gcFId5wDCHfYKa)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/nodejs/build/fbtest.js#L36)):</sup>
weird indentation, no newline

---

<sup>**[nodejs/gulpfile.js, line 6 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpW6BEkU8mymyupb6LH)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/nodejs/gulpfile.js#L6)):</sup>
this closing stuff can be on the prior line

---

<sup>**[nodejs/gulpfile.js, line 11 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpW6FtvbN1a-ryLGvpL)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/nodejs/gulpfile.js#L11)):</sup>
indent

---

<sup>**[nodejs/gulpfile.js, line 19 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpW6LWNXdu1Fc3HNT6p)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/nodejs/gulpfile.js#L19)):</sup>
i don't often see js formatted this way (typically the braces horizontally align with their starting pairs) but i don't think it's actually incorrect

---

<sup>**[nodejs/js/fizzbuzz.js, line 14 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpW6sXNMSvYUUz5CrC-)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/nodejs/js/fizzbuzz.js#L14)):</sup>
isn't this basically what's in the test file? o.O

---

<sup>**[nodejs/js/solution.js, line 3 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpW6vdwiv0RiDTydo2M)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/nodejs/js/solution.js#L3)):</sup>
and this

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8)

**Comment by nicolasartman** [comment]
Review status: all files reviewed, 13 unresolved discussions, all commit checks successful.
Reviewed files:
- .gitignore @ r1
- nodejs/build/fbtest.js @ r1
- nodejs/gulpfile.js @ r1
- nodejs/js/fizzbuzz.js @ r1
- nodejs/js/solution.js @ r1
- nodejs/package.json @ r1
- nodejs/test/fizzbuzz.spec.js @ r1

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8)

**Comment by betaorbust** [comment]
Review status: all files reviewed, 17 unresolved discussions, all commit checks successful.

---

<sup>**[.gitignore, line 5 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpW6gF99ME-fxeV_Bq9)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/.gitignore#L5)):</sup>
https://github.com/github/gitignore/blob/master/Node.gitignore is a good place to start. 

---

<sup>**[nodejs/build/fbtest.js, line 3 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpXz_aVJ0CShFyKaHxV)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/nodejs/build/fbtest.js#L3)):</sup>
Meta point: If you were calling this frequently, you'd want to define your fizzBuzzComputer outside of sodaBee and then reference it inside sodabee, As written, it will make the function every time.

---

<sup>**[nodejs/build/fbtest.js, line 4 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpW4n2_tJFwaUM32xn2)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/nodejs/build/fbtest.js#L4)):</sup>
Indented in spaces, clearly a mistake ;)

---

<sup>**[nodejs/build/fbtest.js, line 5 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpXzMy2hxIjkZKZFIG1)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/nodejs/build/fbtest.js#L5)):</sup>
Mixed double and single quotes.
JS generally falls into the single-quote land.

---

<sup>**[nodejs/build/fbtest.js, line 17 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpW5rhNpqFdw_fxLyCI)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/nodejs/build/fbtest.js#L17)):</sup>
jsdoc, yuidoc, etc. formatted docstrings make a world of difference way down the line. I have a plugin that basically read the method signature, return statements, etc. and pre-populates a doc block for me. (think it's called docblockr?) and I find that immensely helpful in not making docs a chore.

---

<sup>**[nodejs/build/fbtest.js, line 25 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpY-R9JhrUc8029ngDK)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/nodejs/build/fbtest.js#L25)):</sup>
Mixed tabs/spaces. Use only tabs ;)

---

<sup>**[nodejs/gulpfile.js, line 9 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpY-idHkZ3tOpaOkmSP)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/nodejs/gulpfile.js#L9)):</sup>
Totally not necessary for this project, but pulling these src definitions, etc. up into some ALL_CAPS constants up in the top of the file would make it easier to maintain a build script if you were building a large project.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8)

**Comment by nicolasartman** [comment]
Review status: all files reviewed, 17 unresolved discussions, all commit checks successful.

---

<sup>**[nodejs/gulpfile.js, line 9 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpY-idHkZ3tOpaOkmSP)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/nodejs/gulpfile.js#L9)):</sup>
or a config file, which i'm assuming gulp has

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8)

**Comment by adyates** [comment]
Whitespace autocorrected.

---

Review status: 1 of 7 files reviewed, 18 unresolved discussions, all commit checks successful.

---

<sup>**[.gitignore, line 5 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpW6gF99ME-fxeV_Bq9)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/.gitignore#L5)):</sup>
Most of it I don't need yet, but good looking out.

---

<sup>**[nodejs/build/fbtest.js, line 1 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpfL8g8JnfoWgBZP55J)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/nodejs/build/fbtest.js#L1)):</sup>
By the way this entire file is a build artifact so that way I could actually run `mocha` properly.

---

<sup>**[nodejs/build/fbtest.js, line 3 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpXz_aVJ0CShFyKaHxV)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/nodejs/build/fbtest.js#L3)):</sup>
Oh right, Javascript.  I'll move that out because it would probably need to be testable at some point anyway.

---

<sup>**[nodejs/build/fbtest.js, line 5 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpXzMy2hxIjkZKZFIG1)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/nodejs/build/fbtest.js#L5)):</sup>
Yeah, I was winging it with whatever was convenient.  Figured I'd run JSHint once I switched off of emacs =)

---

<sup>**[nodejs/build/fbtest.js, line 6 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpW5_Q10XA0QAKJETEt)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/nodejs/build/fbtest.js#L6)):</sup>
Good to know.  Is there a reason to do so over `+` as a general rule?

---

<sup>**[nodejs/build/fbtest.js, line 10 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpW5KGjDPqk9TEx5uop)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/nodejs/build/fbtest.js#L10)):</sup>
Eh, I'll change to `+=`.  I'm not bugged about it.

---

<sup>**[nodejs/build/fbtest.js, line 18 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpW5zh34yBobffXxvnf)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/nodejs/build/fbtest.js#L18)):</sup>
It is =)

---

<sup>**[nodejs/gulpfile.js, line 9 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpY-idHkZ3tOpaOkmSP)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/nodejs/gulpfile.js#L9)):</sup>
Hilariously, you need a plugin to do the config file.

---

<sup>**[nodejs/gulpfile.js, line 19 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpW6LWNXdu1Fc3HNT6p)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/nodejs/gulpfile.js#L19)):</sup>
Copy/pasta nonsense.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8)

**Comment by nicolasartman** [comment]
Review status: 1 of 5 files reviewed, 17 unresolved discussions, all commit checks successful.

---

<sup>**[nodejs/build/fbtest.js, line 1 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpfL8g8JnfoWgBZP55J)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/nodejs/build/fbtest.js#L1)):</sup>
ahhh :thumbsup: 

---

<sup>**[nodejs/build/fbtest.js, line 6 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpW5_Q10XA0QAKJETEt)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/nodejs/build/fbtest.js#L6)):</sup>
There used to be some perf differences with repeated string concatenation, but I'd bet those have been optimized out at this point. Most of the recent JS I've seen also collects though. I would bet it's a combination of old habits and the alacritous change in frontlandia (both of tech and of requirements, such as how you present a blob of text), meaning it needs to be easy to rapidly identify and swap out the delimiter.

---

<sup>**[nodejs/build/fbtest.js, line 10 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpW5KGjDPqk9TEx5uop)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/nodejs/build/fbtest.js#L10)):</sup>
I looked that up to be sure and it's from a crockford rule: http://stackoverflow.com/questions/971312/why-avoid-increment-and-decrement-operators-in-javascript

I don't think ++ is really evil, but I've been happy with my choice to never use it and haven't missed it at all, so _shrug_.

Some folks also advocate never declaring vars as the init of a for loop. This is to prevent novice programmers from coming along later and getting themselves in a bind by introducing async calls or something inside the loop. Moving the var statement out won't fix that, but it does make the scoping clearer. Since you're in node you may also just be able to use `let`, which is block scoped variable declaration rather than function scoped.

---

<sup>**[nodejs/gulpfile.js, line 9 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpY-idHkZ3tOpaOkmSP)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/nodejs/gulpfile.js#L9)):</sup>
That is...absolutely silly.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8)

**Comment by adyates** [comment]
Review status: 1 of 5 files reviewed, 8 unresolved discussions, all commit checks successful.

---

<sup>**[nodejs/build/fbtest.js, line 0 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpW5KGjDPqk9TEx5uop)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/nodejs/build/fbtest.js#L0)):</sup>
So is this saying "replace `var` with `let`" on it's own, or "move the `var` out of the loop and create a `let` block around that?

---

<sup>**[nodejs/build/fbtest.js, line 0 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpW5rhNpqFdw_fxLyCI)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/nodejs/build/fbtest.js#L0)):</sup>
I'll need to do this later if I decide to start making The Deepest Callback Chain ever, but for now I think it's okay.  I think Eclipse may actually generate the blocks, but I have to look into that a bit more.

---

<sup>**[nodejs/gulpfile.js, line 15 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpY-idHkZ3tOpaOkmSP)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/nodejs/gulpfile.js#L15)):</sup>
Yeah... I'm thinking if I do an HTML/CSS version, I'm going to use grunt to see how annoying it really is.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8)

**Comment by nicolasartman** [comment]
Review status: 1 of 5 files reviewed, 8 unresolved discussions, all commit checks successful.

---

<sup>**[nodejs/build/fbtest.js, line 10 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpW5KGjDPqk9TEx5uop)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/nodejs/build/fbtest.js#L10)):</sup>
the simplest way is just swap `var` for `let`, but node doesn't support `let` in my version (0.12.0) so you could move the var declaration outside and then init it. so

```
var i;
for (i = 0; ...
```

but ultimately i don't think it matters much, since the real solution is to use let once it's widely supported

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8)

**Comment by nicolasartman** [comment]
Review status: 1 of 5 files reviewed, 7 unresolved discussions, all commit checks successful.

---

<sup>**[nodejs/build/fbtest.js, line 17 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpW5rhNpqFdw_fxLyCI)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/nodejs/build/fbtest.js#L17)):</sup>
before you embark on TDCCE, check out q.js

---

<sup>**[nodejs/gulpfile.js, line 9 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpY-idHkZ3tOpaOkmSP)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/nodejs/gulpfile.js#L9)):</sup>
grunt's pretty good.  it's good to try both and see their relative strengths and weaknesses

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8)

**Comment by adyates** [comment]
Review status: 1 of 5 files reviewed, 7 unresolved discussions, all commit checks successful.

---

<sup>**[nodejs/build/fbtest.js, line 0 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpW5rhNpqFdw_fxLyCI)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/nodejs/build/fbtest.js#L0)):</sup>
But.... but... code bowling!

---

<sup>**[nodejs/build/fbtest.js, line 0 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpW5KGjDPqk9TEx5uop)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/nodejs/build/fbtest.js#L0)):</sup>
I feel like this is in The Good Parts as well.  I have vague memories of doing this.

---

<sup>**[nodejs/gulpfile.js, line 15 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpY-idHkZ3tOpaOkmSP)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/nodejs/gulpfile.js#L15)):</sup>
That's basically the plan.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8)

**Comment by nicolasartman** [comment]
Review status: 1 of 5 files reviewed, 7 unresolved discussions, all commit checks successful.

---

<sup>**[nodejs/build/fbtest.js, line 10 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpW5KGjDPqk9TEx5uop)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/nodejs/build/fbtest.js#L10)):</sup>
yea i think it very well may be

---

<sup>**[nodejs/build/fbtest.js, line 17 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpW5rhNpqFdw_fxLyCI)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/nodejs/build/fbtest.js#L17)):</sup>
:banana: is all i have to say to you sir

---

<sup>**[nodejs/gulpfile.js, line 9 [r1]](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8#-JpY-idHkZ3tOpaOkmSP)** ([raw file](https://github.com/adyates/fizzbuzz-the-musical/blob/6ed4684ff569f1568edc5a5461973c75297d9f4f/nodejs/gulpfile.js#L9)):</sup>
:thumbsup: 

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/adyates/fizzbuzz-the-musical/8)

**Pull request merged**
